apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gkuu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-okrt-tenant/rhtap-demo-app/hacbs-test-project-gkuu@sha256:0eb1339f0e9698171b6c979baf322c742c4a1849d54ea36bb202e21fbf2ff30a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
