apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gkuu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-okrt-tenant/rhtap-demo-app/hacbs-test-project-gkuu@sha256:bcdd9b234897933c1b3be95803251dedb2abd4e2d1f8bfc381543e01a4899f84
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
